[project]
name = "databridge"
version = "0.1.0"
description = ""
authors = [
    {name = "majda2001",email = "ablaoui.majda2001@gmail.com"}
]
readme = "README.md"
requires-python == "3.12.1"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "lxml (>=6.0.2,<7.0.0)",
    "xmltodict (>=1.0.3,<2.0.0)",
    "gunicorn (>=25.1.0,<26.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
